### PR TITLE
add checkpoints and dns seeders to improve network.

### PR DESCRIPTION
**Pull request by nagrath**

### CODE REVIEW

**Comment by ghost** [comment]
nAck

1. DNS are not resolvable.
2. Incoherence in chainparams.cpp with newly added checkpoints.
    Checkpoints::CCheckpointData is not initialized with correct data.
3. Rather than deleting the seeds, they should be replaced with new seeds to allow a better 
    connectivity between wallets. (chainparamsseeds.h)
4. I would add a more recent checkpoint. Also choose your checkpoints more wisely. Each 
   checkpoints should be significant enough else it would just slow down the syncing process.

**Comment by nagrath** [comment]
to 1. still driving up seeders :) may take a day till ready before merge this.
to 2. see it o.O my foult, i will fix this ^^
to 3. will be re added if seeders servers are ready
to 4. searching for blocks without transactions and before and after it no tx too. would you use others?

**Comment by ghost** [comment]
Just generated 2 new seeds to add in there: 

   {{0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0xff,0xff,0x90,0xca,0x3c,0xe2}, 40000}
   {{0x20,0x01,0x19,0xf0,0x5c,0x01,0x0b,0x60,0x54,0x00,0x02,0xff,0xfe,0x8e,0x49,0x5f}, 40000}

4. Yes that is fine, as long as they are recent enough and doesn't contain strange transactions.

**Comment by ghost** [comment]
Please add back the deleted seed nodes, they are valid.
Use at least one recent checkpoint from 24 hours ago, this is needed.
Also, the DNS are still not resolvable. Are they configured correctly? Please double check, they should be working by now.

**Comment by nagrath** [comment]
i will re add them.
seeders running, but need a lot of time to gain good connections. Oleg has overview of it, you can see configuration in the seeder git. 
wait with merge until they are fully working

**Comment by ghost** [comment]
Great, seems good now ! :)

**Comment by sc-9310** [comment]
Seeders are running, but partly still no complete dns propagation 
https://www.whatsmydns.net/#NS/scc01.stakecube.net

The bigger problem is crawling good connections, dns requests coming in. The few nodes that are tested are rejected with faulty socket buffer, referring to printf outputs from seeder git
https://github.com/stakecube/stakecubecoin-seeder/blob/master/stakecubecoin.cpp#L246

image

**Comment by nagrath** [comment]
maybe @sipa could help us here? maybe i do some failure with the fork of
the repo https://github.com/stakecube/stakecubecoin-seeder

**Comment by barrystyle** [comment]
yeah, at the moment the issue is the fact that protocol_version has been increased - with no static seeds set that run this new version..

**Pull request closed without merging**
